apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: comp-value
spec:
  serviceName: "postgres"  # StatefulSet과 연동되는 Headless Service 이름
  replicas: 1              # 늘리려면 복제/클러스터링 솔루션과 함께 구성 필요
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      initContainers:
      - name: fix-perms
        image: postgres:15
        command: ["bash","-lc","mkdir -p /var/lib/postgresql/data && chown -R 999:999 /var/lib/postgresql"]
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql
      containers:
      - name: postgres
        image: postgres:15   # 버전 고정(이미지 최신 변경으로 인한 경로/권한 변화 방지)
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: "compvalue"    # 테스트
          - name: POSTGRES_PASSWORD
            value: "compvalue"    # 테스트
          - name: POSTGRES_DB
            value: "COMP_VALUE"
          - name: PGDATA
            value: /var/lib/postgresql/data
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: comp-value
spec:
  clusterIP: None  # Headless Service로 설정
  selector:
    app: postgres  # StatefulSet의 Pod에 붙은 라벨과 일치해야 합니다.
  ports:
    - port: 5432
      targetPort: 5432
