apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: comp-value
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      nodeSelector:
        kubernetes.io/hostname: wk2   # 여기에 wk2 노드 이름을 정확히 넣어줘야 해
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: "compvalue"
          - name: POSTGRES_PASSWORD
            value: "compvalue"
          - name: POSTGRES_DB
            value: "COMP_VALUE"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates: # PVC
  - metadata:
      name: postgres-storage
    spec:
      storageClassName: manual
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi