apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: comp-value
spec:
  clusterIP: None  # Headless Service로 설정
  selector:
    app: postgres  # StatefulSet의 Pod에 붙은 라벨과 일치해야 합니다.
  ports:
    - port: 5432
      targetPort: 5432